# Dockerfile.vite - Dixlase
FROM node:20

WORKDIR /var/www/html

# Copy entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Copy only package.json
COPY ./html/package.json ./

# npm install
RUN npm ci || npm install

# Copy all source code
COPY ./html ./

# Start the Vite server
EXPOSE 5173

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["npm", "run", "dev"]
